# Generated by Django 5.1.7 on 2025-03-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to='image', verbose_name='Картинка')),
                ('content', models.TextField(max_length=1500, verbose_name='Текст новости')),
                ('file_field', models.FileField(upload_to='file', verbose_name='Файл')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('category', models.CharField(choices=[('education', 'образование'), ('society', 'общество'), ('IT', 'ИТ')], max_length=30, verbose_name='Категория')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
